### PR TITLE
Added contributor section

### PR DESCRIPTION
**Pull request by shravya312**
image

### CODE REVIEW

**Comment by sudo-parnab** [comment]
image
What you want to do @shravya312 , It's already exists.
So why should I add this in readme.md?

**Comment by shravya312** [comment]
Ohh Okay I thought it gives better look...when the contributors increase...like 10 or more.

**Comment by shravya312** [comment]
image

**Comment by shravya312** [comment]
If it's not necessary it's fine I will raise some other issue @sudo-parnab

**Comment by sudo-parnab** [comment]
> image it looks like this can u check this @sudo-parnab

But I think, GitHub's own contribution section should have this feature, is it true?

**Comment by shravya312** [comment]
yaa github has but in open source repos.Contributors will be mentioned in the README.md

**Comment by sudo-parnab** [comment]
> If it's not necessary it's fine I will raise some other issue @sudo-parnab

If you wish, you can work with another issue

**Comment by sudo-parnab** [comment]
> yaa github has but in open source repos.Contributors will be mentioned in the README.md

Ok, I am adding it. 👨‍💻

**Comment by sudo-parnab** [comment]
Good work @shravya312

**Comment by shravya312** [comment]
Thanks

**Pull request merged**
